baseurl: https://silvestred.com/
languageCode: en-us
defaultContentLanguage: en
title: Silvestre Dimitrieff
isMultilingual: no
theme: hugo-theme-sam
pygmentsStyle: monokai
pygmentsCodefences: yes
params:
  dateform: Jan 02, 2006
  dateformfull: Jan 2 2006 15:04:05 EST
  description: Silvestre's personal website
  footerText: silvestredim@gmail.com
  homepage: Home
  mainMenu:
    - link: cv
      text: Profile
    - link: work
      text: Work
    - link: reads
      text: Reads
  title: Silvestre Dimitrieff

markup:
  goldmark:
    renderer:
      unsafe: true

