baseurl: https://example.com
languageCode: en-us
defaultContentLanguage: en
isMultilingual: no
title: Silvestre Dimitrieff
theme: hugo-theme-sam
pygmentsStyle: monokai
pygmentsCodefences: yes
params:
  dateform: Mon Jan 02, 2006
  dateformfull: Mon Jan 2 2006 15:04:05 EST
  description: A new Hugo site.
  footerText: silvestredim@gmail.com
  homepage: Home
  mainMenu:
    - link: cv
      text: Profile
    - link: work
      text: Work
    - link: reads
      text: Reads
  title: Silvestre Dimitrieff

markup:
  goldmark:
    renderer:
      unsafe: true

